import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { NavigationProvider } from '@/context/NavigationContext';


export default function App({ Component, pageProps }: AppProps) {
  return (
    <NavigationProvider>
      <Head>
        <title>해피싱크 관리자</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </NavigationProvider>
  );
}
